### ISSUE TITLE
GenericService实例调用非$invoke方法时有数组越界异常

### ISSUE THREAD

**Issue by chenzhiguo** [joyrpc/joyrpc#11]
`@SpringBootApplication
public class BootGeneric {

    public static void main(String[] args) throws Exception{
        System.setProperty("spring.profiles.active", "generic");
        ConfigurableApplicationContext run = SpringApplication.run(BootGeneric.class, args);
        // GenericService consumer = run.getBean(GenericService.class);
        ConsumerConfig<GenericService> consumerConfig = new ConsumerConfig<>();
        RegistryConfig registryConfig = new RegistryConfig("fix");
        registryConfig.setAddress("dubbo://localhost:22000");
        // RegistryConfig registryConfig = new RegistryConfig("broadcast");
        // registryConfig.setAddress("localhost");
        consumerConfig.setRegistry(registryConfig);
        consumerConfig.setGeneric(true);
        consumerConfig.setInterfaceClazz("io.joyrpc.example.service.DemoService");
        consumerConfig.setAlias("2.0-Boot");
        // consumerConfig.setInitSize(5);
        consumerConfig.setLoadbalance("adaptive");
        GenericService consumer = consumerConfig.refer().get();
        System.out.println(consumer.hashCode());   // 异常发生
        Map<String, Object> param = new HashMap<>();
        //header
        Map<String, Object> header = new HashMap<>();
        Map<String, Object> headerAttrs = new HashMap<>();
        headerAttrs.put("type", "generic");
        headerAttrs.put("bodyType", "EchoData");
        header.put("attrs", headerAttrs);
        //body
        Map<String, Object> body = new HashMap<>();
        body.put("code", 1);
        body.put("message", "this is body");
        //body.put("class", "io.joyrpc.example.service.vo.EchoData");
        //param
        param.put("header", header);
        param.put("body", body);

        Object res1 = consumer.$invoke("echoRequest", null, new Object[]{param});
        Object res2 = consumer.$invoke("echoRequestGeneric", null, new Object[]{param});
        Object res3 = consumer.$invoke("echoDataRequest", null, new Object[]{param});

        System.out.println("generic test is end, res is " + res1 + ", " + res2 + ", " + res3);
        /*while (true) {
            try {
                System.out.println(consumer.$invoke("sayHello", null, new Object[]{"helloWold"}));
                Thread.sleep(1000L);
            } catch (InterruptedException e) {
                break;
            } catch (Exception e) {
                try {
                    Thread.sleep(1000L);
                } catch (InterruptedException ex) {
                }
                e.printStackTrace();
            }
        }*/

    }
}`

堆栈信息：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at io.joyrpc.config.AbstractConsumerConfig$ConsumerInvokeHandler.invokeObjectMethod(AbstractConsumerConfig.java:983)
	at io.joyrpc.config.AbstractConsumerConfig$ConsumerInvokeHandler.invoke(AbstractConsumerConfig.java:911)
	at io.joyrpc.config.AbstractConsumerConfig$AbstractConsumerController.invoke(AbstractConsumerConfig.java:835)
	at io.joyrpc.config.AbstractConsumerConfig.lambda$proxy$0(AbstractConsumerConfig.java:262)
	at io.joyrpc.proxy.bytebuddy.ByteBuddyInvocationHandler.invoke(ByteBuddyInvocationHandler.java:65)
	at io.joyrpc.GenericService$ByteBuddy$ZxdFPy6i.hashCode(Unknown Source)
	at io.joyrpc.example.boot.BootGeneric.main(BootGeneric.java:52)

**Comment by hexiaofeng** [comment]
fixed in 1.4.2
