### ISSUE TITLE
Would support discover in applicaiton level rather than service interface level in future?

### ISSUE THREAD

**Issue by helloworlde** [joyrpc/joyrpc#12]
Now, it only support discover in service interface level, and it's hardly to maintain configuration, more and more service interface configuration become mess and error-prone. I think discover in application level is easy to use and ops, then discover service interface automatic, looks it not hard to realize.

**Comment by hexiaofeng** [comment]
done. you can set  serviceName of consumer or provider config. or set global contenxt  appService='xxxxx'. registry use the serviceName.

**Comment by helloworlde** [comment]
Got it, thanks.
